-- Fraud Order Detection And Prevention Module - PostgreSQL schema
-- Apply after the existing ecommerce schema is available.

CREATE TABLE IF NOT EXISTS fraud_assessments (
    id BIGSERIAL PRIMARY KEY,
    uuid VARCHAR(80) NOT NULL UNIQUE,
    version BIGINT,
    order_id BIGINT NOT NULL,
    order_uuid VARCHAR(80),
    customer_id BIGINT,
    vendor_id BIGINT,
    risk_score INTEGER NOT NULL DEFAULT 0,
    risk_level VARCHAR(30) NOT NULL DEFAULT 'LOW',
    decision VARCHAR(50) NOT NULL DEFAULT 'APPROVE',
    status VARCHAR(50) NOT NULL DEFAULT 'REQUESTED',
    decision_reason TEXT,
    evaluation_source VARCHAR(60) NOT NULL DEFAULT 'API',
    evaluation_version VARCHAR(40),
    automatic_decision BOOLEAN NOT NULL DEFAULT TRUE,
    manual_review_required BOOLEAN NOT NULL DEFAULT FALSE,
    evaluated_at TIMESTAMP,
    reviewed_by VARCHAR(120),
    reviewed_at TIMESTAMP,
    review_notes TEXT,
    correlation_id VARCHAR(120),
    idempotency_key VARCHAR(160),
    created_by VARCHAR(120) NOT NULL DEFAULT 'system',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(120),
    modified_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fraud_signals (
    id BIGSERIAL PRIMARY KEY,
    uuid VARCHAR(80) NOT NULL UNIQUE,
    version BIGINT,
    assessment_id BIGINT NOT NULL REFERENCES fraud_assessments(id),
    signal_code VARCHAR(100) NOT NULL,
    signal_category VARCHAR(40) NOT NULL,
    signal_value VARCHAR(500),
    score_impact INTEGER NOT NULL DEFAULT 0,
    triggered BOOLEAN NOT NULL DEFAULT FALSE,
    severity VARCHAR(30) NOT NULL DEFAULT 'INFO',
    source VARCHAR(100),
    reason_code VARCHAR(80),
    detected_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    metadata_json TEXT,
    created_by VARCHAR(120) NOT NULL DEFAULT 'system',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(120),
    modified_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fraud_rules (
    id BIGSERIAL PRIMARY KEY,
    uuid VARCHAR(80) NOT NULL UNIQUE,
    version BIGINT,
    rule_code VARCHAR(100) NOT NULL UNIQUE,
    rule_name VARCHAR(160) NOT NULL,
    description TEXT,
    rule_type VARCHAR(50) NOT NULL,
    signal_code VARCHAR(100),
    rule_operator VARCHAR(40),
    comparison_value VARCHAR(500),
    score_impact INTEGER NOT NULL DEFAULT 0,
    priority INTEGER NOT NULL DEFAULT 100,
    action VARCHAR(60),
    hard_block BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    effective_start_at TIMESTAMP,
    effective_end_at TIMESTAMP,
    vendor_id BIGINT,
    product_id BIGINT,
    category_id BIGINT,
    payment_method VARCHAR(40),
    country VARCHAR(80),
    district VARCHAR(120),
    channel VARCHAR(60),
    rule_configuration_json TEXT,
    created_by VARCHAR(120) NOT NULL DEFAULT 'system',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(120),
    modified_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fraud_cases (
    id BIGSERIAL PRIMARY KEY,
    uuid VARCHAR(80) NOT NULL UNIQUE,
    version BIGINT,
    case_number VARCHAR(60) NOT NULL UNIQUE,
    order_id BIGINT,
    customer_id BIGINT,
    vendor_id BIGINT,
    assessment_id BIGINT REFERENCES fraud_assessments(id),
    case_status VARCHAR(40) NOT NULL DEFAULT 'OPEN',
    priority VARCHAR(30) NOT NULL DEFAULT 'MEDIUM',
    assigned_investigator VARCHAR(120),
    case_reason VARCHAR(500),
    investigation_notes TEXT,
    evidence TEXT,
    resolution VARCHAR(120),
    resolution_reason VARCHAR(1000),
    opened_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP,
    created_by VARCHAR(120) NOT NULL DEFAULT 'system',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(120),
    modified_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fraud_blocklist (
    id BIGSERIAL PRIMARY KEY,
    uuid VARCHAR(80) NOT NULL UNIQUE,
    version BIGINT,
    block_type VARCHAR(50) NOT NULL,
    hashed_value VARCHAR(128) NOT NULL,
    masked_value VARCHAR(160),
    reason VARCHAR(500) NOT NULL,
    scope VARCHAR(40) NOT NULL DEFAULT 'GLOBAL',
    temporary BOOLEAN NOT NULL DEFAULT FALSE,
    expires_at TIMESTAMP,
    created_by_user VARCHAR(120),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by VARCHAR(120) NOT NULL DEFAULT 'system',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(120),
    modified_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fraud_device_identities (
    id BIGSERIAL PRIMARY KEY,
    uuid VARCHAR(80) NOT NULL UNIQUE,
    version BIGINT,
    customer_id BIGINT,
    device_identifier VARCHAR(160) NOT NULL,
    device_fingerprint_hash VARCHAR(128),
    user_agent VARCHAR(500),
    session_identifier VARCHAR(160),
    ip_address VARCHAR(80),
    ip_country VARCHAR(80),
    ip_location VARCHAR(160),
    vpn_indicator BOOLEAN NOT NULL DEFAULT FALSE,
    proxy_indicator BOOLEAN NOT NULL DEFAULT FALSE,
    hosting_indicator BOOLEAN NOT NULL DEFAULT FALSE,
    trusted BOOLEAN NOT NULL DEFAULT FALSE,
    blacklisted BOOLEAN NOT NULL DEFAULT FALSE,
    first_seen_at TIMESTAMP,
    last_seen_at TIMESTAMP,
    metadata_json TEXT,
    created_by VARCHAR(120) NOT NULL DEFAULT 'system',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(120),
    modified_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fraud_trusted_devices (
    id BIGSERIAL PRIMARY KEY,
    uuid VARCHAR(80) NOT NULL UNIQUE,
    version BIGINT,
    customer_id BIGINT NOT NULL,
    device_identifier VARCHAR(160) NOT NULL,
    trusted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    trusted_by VARCHAR(120),
    expires_at TIMESTAMP,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by VARCHAR(120) NOT NULL DEFAULT 'system',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(120),
    modified_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fraud_customer_risk_profiles (
    id BIGSERIAL PRIMARY KEY,
    uuid VARCHAR(80) NOT NULL UNIQUE,
    version BIGINT,
    customer_id BIGINT NOT NULL UNIQUE,
    risk_score INTEGER NOT NULL DEFAULT 0,
    risk_level VARCHAR(30) NOT NULL DEFAULT 'LOW',
    successful_order_count BIGINT NOT NULL DEFAULT 0,
    cancelled_order_count BIGINT NOT NULL DEFAULT 0,
    returned_order_count BIGINT NOT NULL DEFAULT 0,
    refunded_order_count BIGINT NOT NULL DEFAULT 0,
    cod_rto_count BIGINT NOT NULL DEFAULT 0,
    delivery_refusal_count BIGINT NOT NULL DEFAULT 0,
    chargeback_count BIGINT NOT NULL DEFAULT 0,
    lifetime_value NUMERIC(19,4) DEFAULT 0,
    trusted_customer BOOLEAN NOT NULL DEFAULT FALSE,
    blacklisted BOOLEAN NOT NULL DEFAULT FALSE,
    cod_disabled BOOLEAN NOT NULL DEFAULT FALSE,
    last_assessed_at TIMESTAMP,
    created_by VARCHAR(120) NOT NULL DEFAULT 'system',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(120),
    modified_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fraud_vendor_risk_profiles (
    id BIGSERIAL PRIMARY KEY,
    uuid VARCHAR(80) NOT NULL UNIQUE,
    version BIGINT,
    vendor_id BIGINT NOT NULL UNIQUE,
    risk_score INTEGER NOT NULL DEFAULT 0,
    risk_level VARCHAR(30) NOT NULL DEFAULT 'LOW',
    order_count BIGINT NOT NULL DEFAULT 0,
    refund_count BIGINT NOT NULL DEFAULT 0,
    cancel_count BIGINT NOT NULL DEFAULT 0,
    fake_delivery_count BIGINT NOT NULL DEFAULT 0,
    tracking_reuse_count BIGINT NOT NULL DEFAULT 0,
    self_purchase_count BIGINT NOT NULL DEFAULT 0,
    collusion_signal_count BIGINT NOT NULL DEFAULT 0,
    shared_mobile_count BIGINT NOT NULL DEFAULT 0,
    shared_address_count BIGINT NOT NULL DEFAULT 0,
    shared_bank_account_count BIGINT NOT NULL DEFAULT 0,
    unverified_delivery_count BIGINT NOT NULL DEFAULT 0,
    sudden_sales_spike_count BIGINT NOT NULL DEFAULT 0,
    abnormal_refund_rate NUMERIC(7,4) DEFAULT 0,
    abnormal_cancellation_rate NUMERIC(7,4) DEFAULT 0,
    chargeback_exposure NUMERIC(19,4) DEFAULT 0,
    last_risk_reason VARCHAR(500),
    under_review BOOLEAN NOT NULL DEFAULT FALSE,
    payout_held BOOLEAN NOT NULL DEFAULT FALSE,
    last_assessed_at TIMESTAMP,
    created_by VARCHAR(120) NOT NULL DEFAULT 'system',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(120),
    modified_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fraud_review_history (
    id BIGSERIAL PRIMARY KEY,
    uuid VARCHAR(80) NOT NULL UNIQUE,
    version BIGINT,
    assessment_id BIGINT NOT NULL REFERENCES fraud_assessments(id),
    case_id BIGINT,
    previous_decision VARCHAR(50),
    new_decision VARCHAR(50) NOT NULL,
    action VARCHAR(60) NOT NULL,
    reason VARCHAR(500) NOT NULL,
    notes TEXT,
    reviewed_by VARCHAR(120) NOT NULL,
    reviewed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(120) NOT NULL DEFAULT 'system',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(120),
    modified_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fraud_rule_executions (
    id BIGSERIAL PRIMARY KEY,
    uuid VARCHAR(80) NOT NULL UNIQUE,
    version BIGINT,
    assessment_id BIGINT NOT NULL REFERENCES fraud_assessments(id),
    rule_id BIGINT REFERENCES fraud_rules(id),
    rule_code VARCHAR(100) NOT NULL,
    signal_code VARCHAR(100),
    matched BOOLEAN NOT NULL DEFAULT FALSE,
    score_impact INTEGER NOT NULL DEFAULT 0,
    action VARCHAR(60),
    hard_block BOOLEAN NOT NULL DEFAULT FALSE,
    execution_detail_json TEXT,
    executed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(120) NOT NULL DEFAULT 'system',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(120),
    modified_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fraud_event_logs (
    id BIGSERIAL PRIMARY KEY,
    uuid VARCHAR(80) NOT NULL UNIQUE,
    version BIGINT,
    event_type VARCHAR(80) NOT NULL,
    aggregate_type VARCHAR(80),
    aggregate_id BIGINT,
    order_id BIGINT,
    customer_id BIGINT,
    vendor_id BIGINT,
    correlation_id VARCHAR(120),
    idempotency_key VARCHAR(160),
    payload_json TEXT,
    event_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(120) NOT NULL DEFAULT 'system',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(120),
    modified_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fraud_configurations (
    id BIGSERIAL PRIMARY KEY,
    uuid VARCHAR(80) NOT NULL UNIQUE,
    version BIGINT,
    config_key VARCHAR(120) NOT NULL UNIQUE,
    config_value TEXT NOT NULL,
    description VARCHAR(500),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by VARCHAR(120) NOT NULL DEFAULT 'system',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(120),
    modified_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fraud_velocity_counters (
    id BIGSERIAL PRIMARY KEY,
    uuid VARCHAR(80) NOT NULL UNIQUE,
    version BIGINT,
    counter_scope VARCHAR(40) NOT NULL,
    counter_value_hash VARCHAR(128) NOT NULL,
    masked_value VARCHAR(160),
    counter_count BIGINT NOT NULL DEFAULT 0,
    window_start_at TIMESTAMP NOT NULL,
    window_end_at TIMESTAMP NOT NULL,
    created_by VARCHAR(120) NOT NULL DEFAULT 'system',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(120),
    modified_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fraud_payment_risk_results (
    id BIGSERIAL PRIMARY KEY,
    uuid VARCHAR(80) NOT NULL UNIQUE,
    version BIGINT,
    order_id BIGINT,
    payment_id BIGINT,
    provider_name VARCHAR(80),
    provider_status VARCHAR(40) NOT NULL DEFAULT 'NOT_REQUESTED',
    provider_risk_score INTEGER,
    cvv_result VARCHAR(40),
    avs_result VARCHAR(40),
    three_d_secure_result VARCHAR(60),
    authorization_status VARCHAR(60),
    payment_country VARCHAR(80),
    payment_token_hash VARCHAR(128),
    provider_reference VARCHAR(160),
    received_at TIMESTAMP,
    metadata_json TEXT,
    created_by VARCHAR(120) NOT NULL DEFAULT 'system',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(120),
    modified_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fraud_cod_risk_profiles (
    id BIGSERIAL PRIMARY KEY,
    uuid VARCHAR(80) NOT NULL UNIQUE,
    version BIGINT,
    customer_id BIGINT,
    vendor_id BIGINT,
    mobile_hash VARCHAR(128),
    address_hash VARCHAR(128),
    device_identifier VARCHAR(160),
    district VARCHAR(120),
    cod_order_count BIGINT NOT NULL DEFAULT 0,
    cod_success_count BIGINT NOT NULL DEFAULT 0,
    successful_prepaid_order_count BIGINT NOT NULL DEFAULT 0,
    cod_rto_count BIGINT NOT NULL DEFAULT 0,
    delivery_refusal_count BIGINT NOT NULL DEFAULT 0,
    cod_disabled BOOLEAN NOT NULL DEFAULT FALSE,
    customer_cod_limit NUMERIC(19,4),
    vendor_cod_limit NUMERIC(19,4),
    last_delivery_refusal_reason VARCHAR(500),
    last_updated_at TIMESTAMP,
    created_by VARCHAR(120) NOT NULL DEFAULT 'system',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(120),
    modified_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fraud_evidence (
    id BIGSERIAL PRIMARY KEY,
    uuid VARCHAR(80) NOT NULL UNIQUE,
    version BIGINT,
    case_id BIGINT REFERENCES fraud_cases(id),
    assessment_id BIGINT REFERENCES fraud_assessments(id),
    evidence_type VARCHAR(80) NOT NULL,
    title VARCHAR(160) NOT NULL,
    file_name VARCHAR(255),
    file_path VARCHAR(500),
    content_type VARCHAR(120),
    file_size BIGINT,
    note TEXT,
    uploaded_by VARCHAR(120),
    created_by VARCHAR(120) NOT NULL DEFAULT 'system',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(120),
    modified_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fraud_outbox_events (
    id BIGSERIAL PRIMARY KEY,
    uuid VARCHAR(80) NOT NULL UNIQUE,
    version BIGINT,
    event_type VARCHAR(80) NOT NULL,
    aggregate_type VARCHAR(80) NOT NULL,
    aggregate_id BIGINT NOT NULL,
    correlation_id VARCHAR(120),
    idempotency_key VARCHAR(160) NOT NULL UNIQUE,
    payload_json TEXT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    retry_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP,
    published_at TIMESTAMP,
    failure_reason VARCHAR(1000),
    created_by VARCHAR(120) NOT NULL DEFAULT 'system',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(120),
    modified_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fraud_idempotency_records (
    id BIGSERIAL PRIMARY KEY,
    uuid VARCHAR(80) NOT NULL UNIQUE,
    version BIGINT,
    idempotency_key VARCHAR(160) NOT NULL UNIQUE,
    operation_scope VARCHAR(100) NOT NULL,
    request_hash VARCHAR(128),
    status VARCHAR(30) NOT NULL DEFAULT 'STARTED',
    response_json TEXT,
    locked_until TIMESTAMP,
    expires_at TIMESTAMP,
    created_by VARCHAR(120) NOT NULL DEFAULT 'system',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(120),
    modified_at TIMESTAMP
);
