package com.ecommerce.app.module.fraud.model;

public enum FraudPostOrderEventType {
    SHIPMENT_CREATED,
    DELIVERY_CONFIRMED,
    DELIVERY_REFUSAL,
    RETURN_TO_ORIGIN,
    ORDER_CANCELLED,
    REFUND_RELEASED,
    CASHBACK_RELEASED,
    CASHBACK_HELD,
    WALLET_CREDIT_RELEASED,
    WALLET_CREDIT_HELD,
    GIFT_CARD_USAGE,
    REFERRAL_REWARD_RELEASED,
    REFERRAL_REWARD_HELD,
    VENDOR_PAYOUT_REQUESTED,
    VENDOR_PAYOUT_PROCESSING,
    VENDOR_PAYOUT_PAID,
    VENDOR_PAYOUT_HELD,
    VENDOR_RISK_ESCALATED,
    VENDOR_CUSTOMER_COLLUSION,
    TRACKING_REUSE_ATTEMPT,
    FAKE_DELIVERY_SUSPECTED,
    CHARGEBACK_RECORDED,
    RETURN_REQUESTED,
    RETURN_COMPLETED,
    REPLACEMENT_ACTIVITY
}
