package com.ecommerce.app.module.fraud.model;

public enum FraudEventType {
    ORDER_FRAUD_EVALUATION_REQUESTED,
    ORDER_FRAUD_ASSESSMENT_COMPLETED,
    ORDER_FRAUD_APPROVED,
    ORDER_FRAUD_VERIFICATION_REQUIRED,
    ORDER_FRAUD_HELD,
    ORDER_FRAUD_REJECTED,
    CUSTOMER_BLOCKED,
    DEVICE_BLOCKED,
    COD_DISABLED,
    REFUND_HELD,
    VENDOR_PAYOUT_HELD,
    FRAUD_CASE_OPENED,
    FRAUD_CASE_ASSIGNED,
    FRAUD_CASE_RESOLVED,
    FRAUD_AUDIT_RECORDED,
    FRAUD_REVIEW_COMPLETED,
    FRAUD_EVIDENCE_ADDED,
    POST_ORDER_EVENT_RECORDED,
    VALUE_RELEASE_HELD
}
