package com.ecommerce.app.module.fraud.model;

public enum VelocityCounterScope {
    CUSTOMER,
    MOBILE_NUMBER,
    EMAIL,
    DEVICE,
    IP_ADDRESS,
    ADDRESS,
    PAYMENT_TOKEN,
    VENDOR,
    REFERRAL_CODE,
    COUPON_CODE,
    DISTRICT,
    OTP_GUEST_MOBILE_DAILY,
    OTP_CUSTOMER_MOBILE_DAILY,
    OTP_CUSTOMER_ACCOUNT_DAILY,
    OTP_IP_DAILY,
    OTP_DEVICE_DAILY,
    OTP_SESSION_DAILY,
    OTP_GUEST_MOBILE_COOLDOWN,
    OTP_CUSTOMER_ACCOUNT_COOLDOWN,
    OTP_GUEST_MOBILE_CHAIN,
    OTP_CUSTOMER_ACCOUNT_CHAIN,
    OTP_CLAIM_MUTEX
}
